version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

# levantar postgres
# docker-compose up -d postgres

# ver contenedores corriendo
# docker ps

# bajar contenedor
# docker-composer down

# ver logs
# docker-compose logs -f postgres

# Entrar al contenedor
# docker-compose exec postgres bash

# conexión postgres
# psql -h localhost my_db -U root

# Salir de la base de datos
# \q

# levantar pgadmin
# docker-compose up -d pgadmin

# ver ids
# docker ps

# inspeccionar contenedor por id
# docker inspect d5714a0b2dc9
